name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    runs-on: codeberg-tiny
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: ./.forgejo/actions/install-dependencies

      - name: Run tests
        run: make test
