name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: codeberg-tiny
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: 'true'

      - uses: ./.forgejo/actions/install-dependencies

      - name: Run tests
        run: make
